version: 2
workflows:
  version: 2
  test:
    jobs:
      - py27
      - py34
      - py35
      - py36
      - py37
      - pycodestyle
      - cov
jobs:
  py36: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            python -m venv venv || virtualenv venv
            venv/bin/pip install tox
      - run:
          name: Run tests
          command: |
            venv/bin/tox -e $CIRCLE_JOB
  py27:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
  py33:
    <<: *test-template
    docker:
      - image: circleci/python:3.3
  py34:
    <<: *test-template
    docker:
      - image: circleci/python:3.4
  py35:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
  pycodestyle:
    <<: *test-template
  cov:
    <<: *test-template
    environment:
      COVERALLS_REPO_TOKEN: 1H5cGcbtpJbkoe6SI3jwWtiqmJtlt2QAy
